spring:
  redis:
    host: 192.168.194.250   # prueba con esta IP; c√°mbiala si te confirman otra
    port: 6379
server:
  port: 8081                # proxy en 8081 para no chocar con backend
logging:
  level:
    org.springframework.data.redis: INFO
