catedra:
  base-url: "http://192.168.194.250:8080" # REEMPLAZAR con la URL real de la cátedra
  token: "" # opcional: JWT inicial si ya lo tenés
  # refresh-url: "http://192.168.194.250:8080/auth/refresh" # opcional
  # refresh-user: ""
  # refresh-password: ""
  timeout-ms: 5000

spring:
  redis:
    host: 192.168.194.250
    port: 6379
  kafka:
    bootstrap-servers: 192.168.194.250:9092
    consumer:
      group-id: proxy-asientos-group
      auto-offset-reset: earliest

server:
  port: 8081

logging:
  level:
    org.springframework.data.redis: INFO
    org.springframework.kafka: INFO


