spring:
  redis:
    host: 192.168.194.250
    port: 6379
  kafka:
    bootstrap-servers: 192.168.194.250:9092
server:
  port: 8081
logging:
  level:
    org.springframework.data.redis: INFO
    org.springframework.kafka: INFO
