spring:
  redis:
    host: 192.168.194.250
    port: 6379
    database: 0
    ssl: false

server:
  port: 8080

catedra:
  base-url: "http://192.168.194.250:8080"
  ping-on-startup: true

proxy:
  base-url: "http://localhost:8081"
